apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  serviceName: mssql
  replicas: 2
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-18.04
        ports:
        - containerPort: 1433
          name: mssql
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: mssql-config-map
              key: ACCEPT_EULA
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-password
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-storage
          mountPath: "/var/opt/mssql/data"
  volumeClaimTemplates:
  - metadata:
      name: mssql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi