apiVersion: v1
kind: Service
metadata:
  name: fullstackdemoback
spec:
  selector:
    app: fullstackdemoback
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 31000
      targetPort: 80
  
