apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackdemoback
  labels:
    app: fullstackdemoback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstackdemoback
  template:
    metadata:
      labels:
        app: fullstackdemoback
    spec:
      containers:
      - name: fullstackdemoback
        image: houssemromdhani/fullstackdemoback:1.4
        envFrom:
        - configMapRef:
            name: back-config-map
        ports:
        - containerPort: 80
        resources: {}